/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import controller.Controller;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import model.MainObserver;

/**
 *
 * @author pramuditha-lakshan
 */
public class Helicopter extends javax.swing.JFrame implements MainObserver {

    private Controller controller;
    private MainController mainController;
    private String time = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
    private int soldierCount;
    private int ammoCount;
    private int fuel = 100;
    private Clip clip;
    private boolean engineRunning = false;
    private Thread engineThread;

    /**
     * Creates new form Helicopter
     */
    public Helicopter(Controller controller, MainController mainController) {
        initComponents();
        this.controller = controller;
        txtArea.setEditable(false);
        this.mainController = mainController;
        btnShoot.setEnabled(false);
        btnLaser.setEnabled(false);
        btnMissile.setEnabled(false);
        jSlider2.setEnabled(false);
        fuelSpiner.setValue(100);
        engineRunning();
        txtField.grabFocus();

    }

    @Override
    public void updateMessage(String message) {
        txtArea.append(message + "\n");
    }

    @Override
    public void clearArea(boolean clear) {
        if (clear == true) {
            lblArea.setText("Area Cleared");
        } else {
            lblArea.setText("Area Not Cleared");
        }
    }

    @Override
    public void buttonEnable(int value) {
        if (positionCheckBox.isSelected() == true) {
            jSlider2.setValue(value);
            jLabel1.setText(value + "");
            if (value >= 0 || 30 <= value) {
                btnShoot.setEnabled(true);
                btnLaser.setEnabled(false);
                btnMissile.setEnabled(false);
            }
            if (value >= 31 || 60 <= value) {
                btnLaser.setEnabled(true);
                btnShoot.setEnabled(false);
                btnMissile.setEnabled(false);
            }

            if (value >= 61) {
                btnMissile.setEnabled(true);
                btnLaser.setEnabled(false);
                btnShoot.setEnabled(false);
            }
        }
    }

    public String getSoldierCount() {
        return soldierCount + "";
    }

    public String getAmmoCount() {
        return ammoCount + "";
    }

    public String getFuel() {
        return fuel + "";
    }

    public String getPosition() {
        return jSlider2.getValue() + "";
    }

    public void playSound(String path) {
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(getClass().getResource(path));
            clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (Exception ex) {
            Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void sendPrivateMessage(String message) {
        txtArea.append(message + "\n");
    }

    public void engineRunning() {
        if (engineRunning) {
            return;
        }
        engineRunning = true;
        engineThread = new Thread(() -> {
            while (engineRunning) {
                fuelSpiner.setValue(--fuel);
                fuel = (int) fuelSpiner.getValue();
                try {
                    if ((int) fuelSpiner.getValue() <= 0) {
                        engineRunning = false;
                        playSound("/sounds/lowFuel.wav");
                        mainController.getHelicoperMessage("Helicopter - Need to refill");
                        JOptionPane.showMessageDialog(this, "Refill the helicopter", "Low Fuel", JOptionPane.WARNING_MESSAGE);
                        stopSound();
                        break;
                    }
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        engineThread.start();
    }

    private void stopSound() {
        clip.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtField = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnLaser = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fuelSpiner = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        positionCheckBox = new javax.swing.JCheckBox();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ammoSpiner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jButton10.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton10.setText("Send");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        lblArea.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblArea.setText("Area Not Created");

        btnShoot.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnLaser.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnLaser.setText("Laser Operation");
        btnLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserActionPerformed(evt);
            }
        });

        btnMissile.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnMissile.setText("Missile Operation");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Solider Count");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Fuel");

        fuelSpiner.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        fuelSpiner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fuelSpinerStateChanged(evt);
            }
        });

        jSpinner4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        positionCheckBox.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        positionCheckBox.setText("Position");
        positionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCheckBoxActionPerformed(evt);
            }
        });

        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setValue(0);

        jLabel1.setText("Value");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel7.setText("Ammo Count");

        ammoSpiner1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        ammoSpiner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ammoSpiner1StateChanged(evt);
            }
        });

        jLabel2.setText("Current Position - ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLaser)
                                .addGap(59, 59, 59)
                                .addComponent(btnMissile))
                            .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(ammoSpiner1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(positionCheckBox)
                                .addGap(187, 187, 187))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(151, 151, 151)
                                .addComponent(fuelSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(117, 117, 117)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnShoot)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLaser)
                            .addComponent(btnMissile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(positionCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ammoSpiner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fuelSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (txtField.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Enter meessage to send");
        } else {
            playSound("/sounds/messageSend.wav");
            mainController.getHelicoperMessage(time + " - " + txtField.getText());
            txtArea.append(time + " - " + txtField.getText() + "\n");
            txtField.setText("");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        playSound("/sounds/clickSound.wav");
        soldierCount++;
    }//GEN-LAST:event_jSpinner4StateChanged

    private void positionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCheckBoxActionPerformed
        playSound("/sounds/clickSound.wav");
    }//GEN-LAST:event_positionCheckBoxActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        int ammo = (int) ammoSpiner1.getValue();
        if (ammo == 0) {
            JOptionPane.showMessageDialog(this, "Low Ammo");
        } else {
            ammoSpiner1.setValue(--ammoCount);
            playSound("/sounds/Shoot.wav");
        }

    }//GEN-LAST:event_btnShootActionPerformed

    private void btnLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserActionPerformed
        playSound("/sounds/Laser.wav");
    }//GEN-LAST:event_btnLaserActionPerformed

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed
        playSound("/sounds/missile.wav");
    }//GEN-LAST:event_btnMissileActionPerformed

    private void ammoSpiner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ammoSpiner1StateChanged
         playSound("/sounds/CheckBoxClick.wav");
        ammoCount++;
    }//GEN-LAST:event_ammoSpiner1StateChanged

    private void fuelSpinerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fuelSpinerStateChanged
        engineRunning();
        fuel++;
    }//GEN-LAST:event_fuelSpinerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ammoSpiner1;
    private javax.swing.JButton btnLaser;
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnShoot;
    private javax.swing.JSpinner fuelSpiner;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JLabel lblArea;
    private javax.swing.JCheckBox positionCheckBox;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
